server:
  port: 80

spring:
  application:
    name: cloud-order-service
  # 监控的数据要注册到9411上，提前执行：java -jar zipkin-server-x.x.x-exec.jar, 可以访问：http://localhost:9411查看监控页面
  zipkin:
    # 指定监控页面
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率，介于0到1之前，1表示所有数据都采用，速度慢，准确度高，下面取1只是为了学习演示
        probability: 1

eureka:
  client:
    # true表示向注册中心注册自己
    register-with-eureka: true
    # true 表示需要去注册中心检索那些已经注册了的服务, 默认为true. 集群必须设置为true, 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #Eureka注册地址
      #单机版
      defaultZone: http://localhost:7001/eureka/
      #进群版
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/