server:
  port: 80

spring:
  application:
    name: cloud-consul-consumer-order

  ##consule注册中心
  cloud:
    consul:
#      host: vbsos
      host: 10.222.139.92
      port: 8500
      discovery:
        #service-name可以不写，默认就是spring.applicaiton.name
        service-name: ${spring.application.name}
        #当注册到consul是显示service check错误，找原因时发现健康检查访问的地址我本地的ip, 所以制定一下健康检查服务器的host
        health-check-url: http://${spring.cloud.consul.host}:8500

# 如果启动服务有健康检查错误，访问http://10.222.139.92:8500/v1/agent/checks查看原因
