server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com   # Eureka服务端实例域名
  client:
    # false表示不向注册中心注册自己，自己就是注册中心，也是个服务，但是这个服务不注册到自己这里
    register-with-eureka: false
    # false 表示不需要去注册中心检索那些已经注册了的服务
    fetch-registry: false
    service-url:
      #设置地址，7001这个服务，要注册到7002和7003上去
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #单机模式，就是服务地址就是自己
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # 关闭自我保护机制： 默认90秒未发心跳（心跳间隔默认30秒）的服务，则从服务列表中剔除，如果90秒内有大量服务都没有发送心跳，则开启保护机制
    # 保护机制就是，不剔除那些90秒内未发送心跳的服务，依然保持
    enable-self-preservation: false
    # 清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 60000